name: Update flake inputs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-flake:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: Check if flake inputs have changed
        id: check_inputs
        run: |
          git fetch origin
          if git diff --exit-code flake.nix nixpkgs caeleastia-shell; then
            echo "No changes in flake inputs."
            echo "should_update=false" >> $GITHUB_ENV
          else
            echo "Changes detected in flake inputs."
            echo "should_update=true" >> $GITHUB_ENV

      - name: Update flake inputs
        if: env.should_update == 'true'
        run: nix flake update

      - name: Attempt to build flake
        if: env.should_update == 'true'
        run: nix build

      - name: Test on Sway
        if: env.should_update == 'true'
        env:
          XDG_RUNTIME_DIR: /home/runner/runtime
          WLR_BACKENDS: headless
          WLR_LIBINPUT_NO_DEVICES: 1
          WAYLAND_DISPLAY: wayland-1
        run: |
          mkdir $XDG_RUNTIME_DIR
          chown $USER $XDG_RUNTIME_DIR
          chmod 0700 $XDG_RUNTIME_DIR
          nix profile install 'nixpkgs#sway'
          sway &
          sleep 3
          result/bin/caelestia-shell -d
          sleep 3
          pgrep .quickshell-wra
          result/bin/caelestia-shell kill
          killall sway

      - name: Check for changes
        id: check
        run: echo modified=$(git diff --exit-code flake.lock &>/dev/null && echo 'false' || echo 'true') >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.check.outputs.modified == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: flake.lock
          default_author: github_actions
          message: "[CI] chore: update flake"
